export type Trigger = {
  instrument: string
  artist: string
}

export const triggers: Trigger[] = [
  { instrument: 'trumpet', artist: 'Buddy Bolden' },
  { instrument: 'trumpet', artist: 'Freddie Keppard' },
  { instrument: 'trumpet', artist: 'Johnny Dunn' },
  { instrument: 'trumpet', artist: 'King Oliver' },
  { instrument: 'trumpet', artist: 'Louis Armstrong' },
  { instrument: 'trumpet', artist: 'Bix Beiderbecke' },
  { instrument: 'trumpet', artist: 'Rex Stewart' },
  { instrument: 'trumpet', artist: 'Roy Eldridge' },
  { instrument: 'trumpet', artist: 'Dizzy Gillespie' },
  { instrument: 'trumpet', artist: 'Miles Davis' },
  { instrument: 'trumpet', artist: 'Fats Navarro' },
  { instrument: 'trumpet', artist: 'Chet Baker' },
  { instrument: 'trumpet', artist: 'Clifford Brown' },
  { instrument: 'trumpet', artist: 'Blue Mitchell' },
  { instrument: 'trumpet', artist: 'Maynard Ferguson' },
  { instrument: 'trumpet', artist: 'Thad Jones' },
  { instrument: 'trumpet', artist: 'Donald Byrd' },
  { instrument: 'trumpet', artist: 'Woody Shaw' },
  { instrument: 'trumpet', artist: 'Lee Morgan' },
  { instrument: 'trumpet', artist: 'Freddie Hubbard' },
  { instrument: 'trumpet', artist: 'Clark Terry' },
  { instrument: 'trumpet', artist: 'Art Farmer' },
  { instrument: 'trumpet', artist: 'Don Ellis' },
  { instrument: 'trumpet', artist: 'Don Cherry' },
  { instrument: 'trumpet', artist: 'Bill Dixon' },
  { instrument: 'trumpet', artist: 'Michael Mantler' },
  { instrument: 'trumpet', artist: 'Leo Smith' },
  { instrument: 'trumpet', artist: 'Kenny Wheeler' },
  { instrument: 'trumpet', artist: 'Lesli Dalaba' },
  { instrument: 'trumpet', artist: 'Lester Bowie' },
  { instrument: 'trumpet', artist: 'Mark Isham' },
  { instrument: 'trumpet', artist: 'Butch Morris' },
  { instrument: 'trumpet', artist: 'Wynton Marsalis' },
  { instrument: 'trumpet', artist: 'Terence Blanchard' },
  { instrument: 'trumpet', artist: 'Arturo Sandoval' },
  { instrument: 'trumpet', artist: 'Tom Harrell' },
  { instrument: 'trumpet', artist: 'Roy Hargrove' },
  { instrument: 'trumpet', artist: 'Dave Douglas' },
  { instrument: 'trumpet', artist: 'Christian Scott' },
  { instrument: 'trumpet', artist: 'Rob Mazurek' },
  { instrument: 'keyboards', artist: 'Scott Joplin' },
  { instrument: 'keyboards', artist: 'James Johnson' },
  { instrument: 'keyboards', artist: 'Jelly Roll Morton' },
  { instrument: 'keyboards', artist: 'Fats Waller' },
  { instrument: 'keyboards', artist: 'Earl Hines' },
  { instrument: 'keyboards', artist: 'Count Basie' },
  { instrument: 'keyboards', artist: 'Duke Ellington' },
  { instrument: 'keyboards', artist: 'Mary Lou Williams' },
  { instrument: 'keyboards', artist: 'Art Tatum' },
  { instrument: 'keyboards', artist: 'Teddy Wilson' },
  { instrument: 'keyboards', artist: 'Erroll Garner' },
  { instrument: 'keyboards', artist: 'Thelonious Monk' },
  { instrument: 'keyboards', artist: 'John Lewis' },
  { instrument: 'keyboards', artist: 'Bud Powell' },
  { instrument: 'keyboards', artist: 'Lennie Tristano' },
  { instrument: 'keyboards', artist: 'Dave Brubeck' },
  { instrument: 'keyboards', artist: 'George Shearing' },
  { instrument: 'keyboards', artist: 'Oscar Peterson' },
  { instrument: 'keyboards', artist: 'Stan Kenton' },
  { instrument: 'keyboards', artist: 'Horace Silver' },
  { instrument: 'keyboards', artist: 'Cedar Walton' },
  { instrument: 'keyboards', artist: 'Herbie Nichols' },
  { instrument: 'keyboards', artist: 'George Russell' },
  { instrument: 'keyboards', artist: 'Gil Evans' },
  { instrument: 'keyboards', artist: 'Bill Evans' },
  { instrument: 'keyboards', artist: 'Claude Thornhill' },
  { instrument: 'keyboards', artist: 'Jimmy Smith' },
  { instrument: 'keyboards', artist: 'Larry Young' },
  { instrument: 'keyboards', artist: 'Mal Waldron' },
  { instrument: 'keyboards', artist: 'Andrew Hill' },
  { instrument: 'keyboards', artist: 'Don Pullen' },
  { instrument: 'keyboards', artist: 'Cecil Taylor' },
  { instrument: 'keyboards', artist: 'Jaki Byard' },
  { instrument: 'keyboards', artist: 'Tommy Flanagan' },
  { instrument: 'keyboards', artist: 'Stanley Cowell' },
  { instrument: 'keyboards', artist: 'Kenny Barron' },
  { instrument: 'keyboards', artist: 'Hank Jones' },
  { instrument: 'keyboards', artist: 'Myra Melford' },
  { instrument: 'keyboards', artist: 'Marilyn Crispell' },
  { instrument: 'keyboards', artist: 'Joanne Brackeen' },
  { instrument: 'keyboards', artist: 'Sun Ra' },
  { instrument: 'keyboards', artist: 'Dollar Brand' },
  { instrument: 'keyboards', artist: 'Chick Corea' },
  { instrument: 'keyboards', artist: 'Herbie Hancock' },
  { instrument: 'keyboards', artist: 'Paul Bley' },
  { instrument: 'keyboards', artist: 'McCoy Tyner' },
  { instrument: 'keyboards', artist: 'Joe Zawinul' },
  { instrument: 'keyboards', artist: 'Carla Bley' },
  { instrument: 'keyboards', artist: 'Keith Jarrett' },
  { instrument: 'keyboards', artist: 'Muhal Richard Abrams' },
  { instrument: 'keyboards', artist: 'Amina-Claudine Myers' },
  { instrument: 'keyboards', artist: 'Richard Teitelbaum' },
  { instrument: 'keyboards', artist: 'Anthony Davis' },
  { instrument: 'keyboards', artist: 'Wayne Horvitz' },
  { instrument: 'keyboards', artist: 'Lyle Mays' },
  { instrument: 'keyboards', artist: 'Misha Mengelberg' },
  { instrument: 'keyboards', artist: 'Irene Schweizer' },
  { instrument: 'keyboards', artist: 'Matthew Shipp' },
  { instrument: 'keyboards', artist: 'Geri Allen' },
  { instrument: 'keyboards', artist: 'Martial Solal' },
  { instrument: 'keyboards', artist: 'Paul Plimley' },
  { instrument: 'keyboards', artist: 'Jessica Williams' },
  { instrument: 'keyboards', artist: 'Brad Mehldau' },
  { instrument: 'keyboards', artist: 'Jason Moran' },
  { instrument: 'keyboards', artist: 'Vijay Iver' },
  { instrument: 'keyboards', artist: 'Fred Hersch' },
  { instrument: 'keyboards', artist: 'Hiromi' },
  { instrument: 'drums', artist: 'Buddy Rich' },
  { instrument: 'drums', artist: 'Gene Kupra' },
  { instrument: 'drums', artist: 'Kenny Clarke' },
  { instrument: 'drums', artist: 'Roy Haynes' },
  { instrument: 'drums', artist: 'Shelly Manne' },
  { instrument: 'drums', artist: 'Chico Hamilton' },
  { instrument: 'drums', artist: 'Art Blakey' },
  { instrument: 'drums', artist: 'Max Roach' },
  { instrument: 'drums', artist: 'Lionel Hampton' },
  { instrument: 'drums', artist: 'Philly Joe Jones' },
  { instrument: 'drums', artist: 'Mel Lewis' },
  { instrument: 'drums', artist: 'Elvin Jones' },
  { instrument: 'drums', artist: 'Ed Blackwell' },
  { instrument: 'drums', artist: 'Milford Graves' },
  { instrument: 'drums', artist: 'Barry Altschul' },
  { instrument: 'drums', artist: 'Andrew Cyrille' },
  { instrument: 'drums', artist: 'Rashied Ali' },
  { instrument: 'drums', artist: 'Sunny Murray' },
  { instrument: 'drums', artist: 'Tony Williams' },
  { instrument: 'drums', artist: 'Don Moye' },
  { instrument: 'drums', artist: 'Paul Motian' },
  { instrument: 'drums', artist: 'Jack DeJohnette' },
  { instrument: 'drums', artist: 'Billy Cobham' },
  { instrument: 'drums', artist: 'Sam Bennett' },
  { instrument: 'drums', artist: 'Trilok Gurtu' },
  { instrument: 'drums', artist: 'Glen Velez' },
  { instrument: 'drums', artist: 'Nana Vasconcelos' },
  { instrument: 'drums', artist: 'Michael Shrieve' },
  { instrument: 'drums', artist: 'Stomu Yamashta' },
  { instrument: 'drums', artist: 'Gerry Hemingway' },
  { instrument: 'drums', artist: 'Ronald Shannon Jackson' },
  { instrument: 'drums', artist: 'Tony Oxley' },
  { instrument: 'drums', artist: 'Han Bennink' },
  { instrument: 'drums', artist: 'Paul Lovens' },
  { instrument: 'drums', artist: 'William Hooker' },
  { instrument: 'drums', artist: 'David Moss' },
  { instrument: 'drums', artist: 'Charles Noyes' },
  { instrument: 'drums', artist: 'Ikue Mori' },
  { instrument: 'drums', artist: 'Bobby Previte' },
  { instrument: 'drums', artist: 'Peter Erskine' },
  { instrument: 'drums', artist: 'Danny Gottlieb' },
  { instrument: 'drums', artist: 'Chris Corsano' },
  { instrument: 'guitar', artist: 'Freddie Green' },
  { instrument: 'guitar', artist: 'Eddie Lang' },
  { instrument: 'guitar', artist: 'Django Reinhardt' },
  { instrument: 'guitar', artist: 'Charlie Christian' },
  { instrument: 'guitar', artist: 'Eddie Condon' },
  { instrument: 'guitar', artist: 'Kenny Burrell' },
  { instrument: 'guitar', artist: 'Wes Montgomery' },
  { instrument: 'guitar', artist: 'Jim Hall' },
  { instrument: 'guitar', artist: 'Joe Pass' },
  { instrument: 'guitar', artist: 'Eddie Durham' },
  { instrument: 'guitar', artist: 'Larry Coryell' },
  { instrument: 'guitar', artist: 'John McLaughlin' },
  { instrument: 'guitar', artist: 'John Abercrombie' },
  { instrument: 'guitar', artist: 'George Benson' },
  { instrument: 'guitar', artist: 'Derek Bailey' },
  { instrument: 'guitar', artist: 'Keith Rowe' },
  { instrument: 'guitar', artist: 'Eugene Chadbourne' },
  { instrument: 'guitar', artist: 'Kevin Drumm' },
  { instrument: 'guitar', artist: 'Ralph Towner' },
  { instrument: 'guitar', artist: 'David Torn' },
  { instrument: 'guitar', artist: 'Steve Tibbetts' },
  { instrument: 'guitar', artist: 'Nels Cline' },
  { instrument: 'guitar', artist: 'Fred Frith' },
  { instrument: 'guitar', artist: 'Pat Metheny' },
  { instrument: 'guitar', artist: 'James Blood Ulmer' },
  { instrument: 'guitar', artist: 'Sonny Sharrock' },
  { instrument: 'guitar', artist: 'Al DiMeola' },
  { instrument: 'guitar', artist: 'John Scofield' },
  { instrument: 'guitar', artist: 'Elliott Sharp' },
  { instrument: 'guitar', artist: 'Alan Licht' },
  { instrument: 'guitar', artist: 'Jon Rose' },
  { instrument: 'guitar', artist: 'Henry Kaiser' },
  { instrument: 'guitar', artist: 'Bill Frisell' },
  { instrument: 'guitar', artist: 'Mike Stern' },
  { instrument: 'guitar', artist: 'Stanley Jordan' },
  { instrument: 'guitar', artist: 'Mary Halvorson' },
  { instrument: 'bass', artist: 'Steve Brown ' },
  { instrument: 'bass', artist: 'John Kirby ' },
  { instrument: 'bass', artist: 'Walter Page' },
  { instrument: 'bass', artist: 'Jimmy Blanton ' },
  { instrument: 'bass', artist: 'Milt Hinton' },
  { instrument: 'bass', artist: 'Milt Jackson ' },
  { instrument: 'bass', artist: 'Percy Heath' },
  { instrument: 'bass', artist: 'Charles Mingus' },
  { instrument: 'bass', artist: 'Scott LaFaro' },
  { instrument: 'bass', artist: 'Ron Carter' },
  { instrument: 'bass', artist: 'Stanley Clarke' },
  { instrument: 'bass', artist: 'Steve Swallow' },
  { instrument: 'bass', artist: 'Jamaladeen Tacuma' },
  { instrument: 'bass', artist: 'Eberhard Weber' },
  { instrument: 'bass', artist: 'Charlie Haden' },
  { instrument: 'bass', artist: 'Cecil McBee' },
  { instrument: 'bass', artist: 'David Friesen' },
  { instrument: 'bass', artist: 'Dave Holland' },
  { instrument: 'bass', artist: 'Jaco Pastorius' },
  { instrument: 'bass', artist: `Patrick O'Hearn` },
  { instrument: 'bass', artist: 'Bob Wasserman' },
  { instrument: 'bass', artist: 'Mark Helias' },
  { instrument: 'bass', artist: 'Maarten Altena' },
  { instrument: 'bass', artist: 'Peter Kowald' },
  { instrument: 'bass', artist: 'Saheb Sarbib' },
  { instrument: 'bass', artist: 'Marc Johnson' },
  { instrument: 'bass', artist: 'Mark Egan' },
  { instrument: 'bass', artist: 'Reggie Workman' },
  { instrument: 'bass', artist: 'John Patitucci' },
  { instrument: 'bass', artist: 'Michael Formanek' },
  { instrument: 'bass', artist: 'Christian McBride' },
  { instrument: 'bass', artist: 'Marcus Miller' },
  { instrument: 'bass', artist: 'Victor Wooten' },
  { instrument: 'bass', artist: 'Christian McBride' },
  { instrument: 'bass', artist: 'Esperanza Spalding' },
  { instrument: 'flute', artist: 'Wayne Carver' },
  { instrument: 'flute', artist: 'Bud Shank' },
  { instrument: 'flute', artist: 'Herbie Mann' },
  { instrument: 'flute', artist: 'Roland Kirk' },
  { instrument: 'flute', artist: 'Eric Dolphy' },
  { instrument: 'flute', artist: 'Yusef Lateef' },
  { instrument: 'flute', artist: 'Paul Horn' },
  { instrument: 'flute', artist: 'Hubert Laws' },
  { instrument: 'flute', artist: 'Sonny Fortune' },
  { instrument: 'flute', artist: 'James Spaulding' },
  { instrument: 'flute', artist: 'James Newton' },
  { instrument: 'flute', artist: 'Robert Dick' },
  { instrument: 'flute', artist: 'Dave Valentin' },
  { instrument: 'flute', artist: 'Frank Wess' },
  { instrument: 'flute', artist: 'Henry Threadgill' },
  { instrument: 'tenor saxophone', artist: 'Coleman Hawkins' },
  { instrument: 'tenor saxophone', artist: 'Lester Young' },
  { instrument: 'tenor saxophone', artist: 'Ben Webster' },
  { instrument: 'tenor saxophone', artist: 'Hank Mobley' },
  { instrument: 'tenor saxophone', artist: 'Tina Brooks' },
  { instrument: 'tenor saxophone', artist: 'Dexter Gordon' },
  { instrument: 'tenor saxophone', artist: 'Oliver Nelson' },
  { instrument: 'tenor saxophone', artist: 'Stan Getz' },
  { instrument: 'tenor saxophone', artist: 'Zoot Sims' },
  { instrument: 'tenor saxophone', artist: 'Sonny Rollins' },
  { instrument: 'tenor saxophone', artist: 'Wayne Shorter' },
  { instrument: 'tenor saxophone', artist: 'John Coltrane' },
  { instrument: 'tenor saxophone', artist: 'Albert Ayler' },
  { instrument: 'tenor saxophone', artist: 'Archie Shepp' },
  { instrument: 'tenor saxophone', artist: 'Sam Rivers' },
  { instrument: 'tenor saxophone', artist: 'John Gilmore' },
  { instrument: 'tenor saxophone', artist: 'Pharoah Sanders' },
  { instrument: 'tenor saxophone', artist: 'Kalaparush Maurice McIntyre' },
  { instrument: 'tenor saxophone', artist: 'Fred Anderson' },
  { instrument: 'tenor saxophone', artist: 'Gato Barbieri' },
  { instrument: 'tenor saxophone', artist: 'Joe Henderson' },
  { instrument: 'tenor saxophone', artist: 'David Murray' },
  { instrument: 'tenor saxophone', artist: 'Michael Brecker' },
  { instrument: 'tenor saxophone', artist: 'Chico Freeman' },
  { instrument: 'tenor saxophone', artist: 'Frank Lowe' },
  { instrument: 'tenor saxophone', artist: 'Joe McPhee' },
  { instrument: 'tenor saxophone', artist: 'Joe Henderson' },
  { instrument: 'tenor saxophone', artist: 'Branford Marsalis' },
  { instrument: 'tenor saxophone', artist: 'James Carter' },
  { instrument: 'tenor saxophone', artist: 'John Butcher' },
  { instrument: 'tenor saxophone', artist: 'Joe Lovano' },
  { instrument: 'tenor saxophone', artist: 'Marty Fogel' },
  { instrument: 'tenor saxophone', artist: 'Larry Ochs' },
  { instrument: 'tenor saxophone', artist: 'Ken Vandermark' },
  { instrument: 'tenor saxophone', artist: 'Joshua Redman' },
  { instrument: 'tenor saxophone', artist: 'Gary Thomas' },
  { instrument: 'alto saxophone', artist: 'Johnny Hodges' },
  { instrument: 'alto saxophone', artist: 'Benny Carter' },
  { instrument: 'alto saxophone', artist: 'Charlie Parker' },
  { instrument: 'alto saxophone', artist: 'Lee Konitz' },
  { instrument: 'alto saxophone', artist: 'Paul Desmond' },
  { instrument: 'alto saxophone', artist: 'Art Pepper' },
  { instrument: 'alto saxophone', artist: 'Marion Brown' },
  { instrument: 'alto saxophone', artist: 'Cannonball Adderley' },
  { instrument: 'alto saxophone', artist: 'Phil Woods' },
  { instrument: 'alto saxophone', artist: 'Jackie McLean' },
  { instrument: 'alto saxophone', artist: 'Ornette Coleman' },
  { instrument: 'alto saxophone', artist: 'Eric Dolphy' },
  { instrument: 'alto saxophone', artist: 'Paul Winter' },
  { instrument: 'alto saxophone', artist: 'John Tchicai' },
  { instrument: 'alto saxophone', artist: 'Jimmy Lyons' },
  { instrument: 'alto saxophone', artist: 'Anthony Braxton' },
  { instrument: 'alto saxophone', artist: 'Roscoe Mitchell' },
  { instrument: 'alto saxophone', artist: 'Joseph Jarman' },
  { instrument: 'alto saxophone', artist: 'Julius Hemphill' },
  { instrument: 'alto saxophone', artist: 'Oliver Lake' },
  { instrument: 'alto saxophone', artist: 'Arthur Blythe' },
  { instrument: 'alto saxophone', artist: 'Joe Harriott' },
  { instrument: 'alto saxophone', artist: 'Tim Berne' },
  { instrument: 'alto saxophone', artist: 'John Zorn' },
  { instrument: 'alto saxophone', artist: 'Marty Ehrlich' },
  { instrument: 'alto saxophone', artist: 'Henry Threadgill' },
  { instrument: 'alto saxophone', artist: 'Steve Coleman' },
  { instrument: 'alto saxophone', artist: 'Greg Osby' },
  { instrument: 'alto saxophone', artist: 'James Spaulding' },
  { instrument: 'alto saxophone', artist: 'Rudresh Mahanthappa' },
  { instrument: 'baritone saxophone', artist: 'Gerry Mulligan' },
  { instrument: 'baritone saxophone', artist: 'Pepper Adams' },
  { instrument: 'baritone saxophone', artist: 'Hamiett Bluiett' },
  { instrument: 'baritone saxophone', artist: 'Steve Lacy' },
  { instrument: 'baritone saxophone', artist: 'Lol Coxhill' },
  { instrument: 'baritone saxophone', artist: 'Dave Liebman' },
  { instrument: 'baritone saxophone', artist: 'Branford Marsalis' },
  { instrument: 'baritone saxophone', artist: 'John Surman ' },
  { instrument: 'baritone saxophone', artist: 'Evan Parker' },
  { instrument: 'baritone saxophone', artist: 'Jon Raskin' },
  { instrument: 'baritone saxophone', artist: 'Dave Liebman ' },
  { instrument: 'baritone saxophone', artist: 'Gary Smulyan' },
  { instrument: 'clarinet', artist: 'Barney Bigard' },
  { instrument: 'clarinet', artist: 'Johnny Dodds' },
  { instrument: 'clarinet', artist: 'Jimmie Noone' },
  { instrument: 'clarinet', artist: 'Sidney Bechet' },
  { instrument: 'clarinet', artist: 'Pee Wee Russell' },
  { instrument: 'clarinet', artist: 'Benny Goodman' },
  { instrument: 'clarinet', artist: 'Woody Herman' },
  { instrument: 'clarinet', artist: 'Artie Shaw' },
  { instrument: 'clarinet', artist: 'Jimmy Dorsey' },
  { instrument: 'clarinet', artist: 'Tony Scott' },
  { instrument: 'clarinet', artist: 'Buddy DeFranco' },
  { instrument: 'clarinet', artist: 'Jimmy Giuffre' },
  { instrument: 'clarinet', artist: 'Eric Dolphy' },
  { instrument: 'clarinet', artist: 'Marty Ehrlich' },
  { instrument: 'clarinet', artist: 'Don Byron' },
  { instrument: 'clarinet', artist: 'Guillermo Gregorio' },
  { instrument: 'clarinet', artist: 'Anat Cohen' },
  { instrument: 'clarinet', artist: 'Ken Peplowski' },
  { instrument: 'clarinet', artist: `Paquito D'Rivera` },
  { instrument: 'trombone', artist: 'Kid Ory' },
  { instrument: 'trombone', artist: 'Miff Mole' },
  { instrument: 'trombone', artist: 'Tommy Dorsey' },
  { instrument: 'trombone', artist: 'Jack Teargarden' },
  { instrument: 'trombone', artist: 'Kai Winding' },
  { instrument: 'trombone', artist: 'Bob Brookmeyer' },
  { instrument: 'trombone', artist: 'J.J. Johnson' },
  { instrument: 'trombone', artist: 'Bill Harris' },
  { instrument: 'trombone', artist: 'Roswell Rudd' },
  { instrument: 'trombone', artist: 'Curtis Fuller' },
  { instrument: 'trombone', artist: 'George Lewis' },
  { instrument: 'trombone', artist: 'Jim Staley' },
  { instrument: 'trombone', artist: 'Ray Anderson' },
  { instrument: 'trombone', artist: 'Peter Zummo' },
  { instrument: 'trombone', artist: 'Jimmy Knepper' },
  { instrument: 'trombone', artist: 'Robin Eubanks' },
  { instrument: 'trombone', artist: 'Julian Priester' },
  { instrument: 'trombone', artist: 'Albert Mangelsdorff' },
  { instrument: 'trombone', artist: 'Guenter Christmann' },
  { instrument: 'trombone', artist: 'Paul Rutherford' },
  { instrument: 'trombone', artist: 'Steve Turre' },
  { instrument: 'trombone', artist: 'Conrad Herwig' },
  { instrument: 'groups', artist: 'Original Dixieland Jass Band' },
  { instrument: 'groups', artist: 'Modern Jazz Quartet' },
  { instrument: 'groups', artist: 'Jazztet' },
  { instrument: 'groups', artist: 'Art Ensemble Of Chicago' },
  { instrument: 'groups', artist: 'Air' },
  { instrument: 'groups', artist: 'Mahavishnu Orchestra' },
  { instrument: 'groups', artist: 'Revolutionary Ensemble' },
  { instrument: 'groups', artist: 'World Saxophone Quartet' },
  { instrument: 'groups', artist: 'Weather Report' },
  { instrument: 'groups', artist: 'Oregon' },
  { instrument: 'groups', artist: 'Yellowjackets' },
  { instrument: 'groups', artist: 'Spyro Gyra' },
  { instrument: 'groups', artist: 'Shadowfax' },
  { instrument: 'groups', artist: 'Group 87' },
  { instrument: 'groups', artist: 'Montreux' },
  { instrument: 'groups', artist: 'Turtle Island String Quartet' },
  { instrument: 'groups', artist: 'Curlew' },
  { instrument: 'groups', artist: 'Borbetomagus' },
  { instrument: 'groups', artist: 'Necks' },
  { instrument: 'vocals', artist: 'Louis Armstrong' },
  { instrument: 'vocals', artist: 'Billie Holiday' },
  { instrument: 'vocals', artist: 'Ella Fitzgerald' },
  { instrument: 'vocals', artist: 'Frank Sinatra' },
  { instrument: 'vocals', artist: 'Nat King Cole' },
  { instrument: 'vocals', artist: 'Billy Eckstine' },
  { instrument: 'vocals', artist: 'Sarah Vaughan' },
  { instrument: 'vocals', artist: 'Betty Carter' },
  { instrument: 'vocals', artist: 'Carmen McRae' },
  { instrument: 'vocals', artist: 'Shirley Horn' },
  { instrument: 'vocals', artist: 'Abbey Lincoln' },
  { instrument: 'vocals', artist: 'Patty Waters' },
  { instrument: 'vocals', artist: 'Jeanne Lee' },
  { instrument: 'vocals', artist: 'Jay Clayton' },
  { instrument: 'vocals', artist: 'Bobby McFerrin' },
  { instrument: 'vocals', artist: 'Al Jarreau' },
  { instrument: 'vocals', artist: 'Sheila Jordan' },
  { instrument: 'vocals', artist: 'Cassandra Wilson' },
  { instrument: 'vocals', artist: 'Diana Krall' },
  { instrument: 'vocals', artist: 'Dianne Reeves' },
  { instrument: 'vocals', artist: 'Kurt Elling' },
  { instrument: 'violin', artist: 'Stuff Smith' },
  { instrument: 'violin', artist: 'Joe Venuti' },
  { instrument: 'violin', artist: 'Stephane Grappelly' },
  { instrument: 'violin', artist: 'Jean-Luc Ponty' },
  { instrument: 'violin', artist: 'Leroy Jenkins' },
  { instrument: 'violin', artist: 'Billy Bang' },
  { instrument: 'violin', artist: 'Mark Feldman' },
  { instrument: 'violin', artist: 'Regina Carter' },
  { instrument: 'harp', artist: 'Alice Coltrane' },
  { instrument: 'harp', artist: 'Zeena Parkins' },
  { instrument: 'accordion', artist: 'Guy Klucevsek' },
  { instrument: 'accordion', artist: 'Richard Galliano' },
  { instrument: 'vibraphone', artist: 'Lionel Hampton' },
  { instrument: 'vibraphone', artist: 'Red Norvo' },
  { instrument: 'vibraphone', artist: 'Milt Jackson' },
  { instrument: 'vibraphone', artist: 'Teddy Charles' },
  { instrument: 'vibraphone', artist: 'Cal Tjader' },
  { instrument: 'vibraphone', artist: 'Bobby Hutcherson' },
  { instrument: 'vibraphone', artist: 'Gary Burton' },
  { instrument: 'vibraphone', artist: 'Gunter Hampel' },
  { instrument: 'vibraphone', artist: 'Stefon Harris' },
  { instrument: 'cello', artist: 'Fred Katz' },
  { instrument: 'cello', artist: 'Collin Walcott' },
  { instrument: 'cello', artist: 'David Darling' },
  { instrument: 'cello', artist: 'Tom Cora' },
  { instrument: 'cello', artist: 'Hank Roberts' },
  { instrument: 'cello', artist: 'Erik Friedlander' },
  { instrument: 'cello', artist: 'Fred Lonberg-Holm' },
  { instrument: 'cello', artist: 'Okkyung Lee ' },
  { instrument: 'banjo', artist: 'Bela Fleck' },
  { instrument: 'piano', artist: 'Joey Alexander' },
]
