export const blankSpot = '_____ '

// Most of these sourced from https://linguazza.com/sentences-with/blank+spots
export default [
  `I've got your ${blankSpot} right here.`,
  `Oh, someone's got ${blankSpot} on the mind.`,
  `PAUSE.`,
  `Put your money where your ${blankSpot} is.`,
  `Mmmmm ${blankSpot}`,
  `Get your hand off my ${blankSpot}`,
  `A wild ${blankSpot} has appeared`,
  `404 error ${blankSpot} not found`,
  `SHEEEEEEEEESH`,
  `${blankSpot} - part of a complete breakfast!`,
  `Most aim to treat macular degeneration, a common disorder among older people in which blurriness starts at the center of the visual field and produces a permanent ${blankSpot}.`,
  `Kind of beats the hell out that 9-to-5 gig, wearing a coat and tie, staring at the ${blankSpot} in your cubicle, and suddenly realizing you are only in your mid-30s and there is another 24 years before you get that company going away party, doesn't it?`,
  `If you didn't enable Shelf when you set up your OnePlus 5T, you just need to find a ${blankSpot} on your home screen and long press.`,
  `Last year, Google erected the big blue ${blankSpot} on its online replica of the Earth with three-dimensional oceans.`,
  `Now, geophysicists at Columbia University's Lamont-Doherty Earth Observatory in Palisades, New York, plan to erect the giant ${blankSpot}, using an ultrasensitive airborne gravity detector.`,
  `Whether your current love map is a topographical masterpiece or just a rough sketch, you can improve your connection to the one you love starting today by filling in the ${blankSpot}s.`,
  `Over time, it can grow to full-on ${blankSpot}s, making it difficult or impossible to perform daily activities like reading or driving.`,
  `A new deep-field photo of a ${blankSpot} in space unveils thousands of previously unseen primordial galaxies.`,
  `Seismologists now admit that the part of the fault nearest the island of Okushiri was a ${blankSpot} which they had not expected to rupture.`,
  `Scientists at Columbia's Lamont-Doherty Earth Observatory have found evidence of hydrothermal vents on the seafloor near Antarctica, formerly a ${blankSpot} on the map for researchers wanting to learn more about seafloor formation and the bizarre life forms drawn to these extreme environments.`,
  `Falling rubble had damaged one of the cameras, leaving a ${blankSpot} in the visual field, but even so, the film received tremendous media attention.`,
  `The homework acts like a kind of Madlib, with players filling in ${blankSpot}s in biographical papers on historical people.`,
  `Nervously using LOL, or OMG for that matter, to avoid ${blankSpot}s in the conversation is a no-no.`,
  `Today, the company wrapped a real home for sale in Austin, Texas, leaving a giant ${blankSpot} on the block, asserting that if you only search Zillow, you may be missing out on your dream home.`,
  `In many different ways, the project plays with the ${blankSpot}s in our knowledge of American history.`,
  `Unfortunately the techniques used up to this point have left this model riddled with ${blankSpot}s, but here is a brief outline of our galaxy as it is currently understood.`,
  `It has irritating moments of preciousness and ${blankSpot}s where it dwindles off into inconsequentiality.`,
  `Alongside pictures of Resident Evil 7, Resident Evil Revelations, and Resident Evil Revelations 2, a ${blankSpot} was conveniently added that had many believing a new game was waiting in the wings to be announced.`,
  `You realize how many worlds there are from the way the ${blankSpot}s are arranged on the map.`,
  `It seems that my whole life has been leading up to having the book published and so, perhaps, that explains why there are so many ${blankSpot}s.`,
  `The Note 8 was certainly worth the wait as it received their largest Infinity Display, lost its physical home button to on-screen buttons, and received the smallest top and bottom bezels you have ever seen — it's a shame that Samsung did not include a bottom, front-facing speaker in an area where there is a ${blankSpot}.`,
  `They experience ${blankSpot}s in their driving all the time, sometimes at 60 miles per hour.`,
  `You just need to long press the ${blankSpot} on your home screen to pull up the launcher edit buttons.`,
  ``,
]
