export interface Synonym {
  label: string
  replace?: string[]
  exactMatch?: boolean
}

export const synonyms: Synonym[] = [
  { label: '2x4' },
  { label: '9-iron' },
  { label: 'aardvark' },
  { label: 'acorn', replace: ['acorn top'] },
  { label: 'anaconda' },
  { label: 'antenna' },
  {
    label: 'apple',
    replace: [
      'apple head',
      'apple-headed beef basher',
      'apple on a short branch',
    ],
  },
  { label: 'arrow', replace: [`cupid's arrow`] },
  { label: 'aux cord' },
  { label: 'baby', replace: ['baby leg', 'baby maker'] },
  { label: 'back scratcher' },
  { label: 'banana' },
  { label: 'bandit' },
  { label: 'banjo' },
  { label: 'baton' },
  { label: 'bazooka' },
  { label: 'beak', replace: [`flamingo's beak`] },
  { label: 'beanie baby' },
  { label: 'beanstalk' },
  { label: 'bear', replace: ['hibernating bear'] },
  {
    label: 'beast',
    replace: [
      'beast of burden',
      'below the belt bacon beast',
      'beefy bastard',
      'wrinklebeast',
    ],
  },
  { label: 'bigfoot' },
  { label: 'binky' },
  { label: 'blade', replace: ['mighty blade', 'blade'] },
  { label: 'blimp', replace: ['fur blimp'] },
  { label: 'blowpop' },
  { label: 'blunderbuss' },
  { label: 'bone' },
  { label: 'bouquet', replace: ['one flower bouquet'] },
  { label: 'branch', replace: ['fuck stick', 'glue stick', 'gut stick'] },
  { label: 'brick', replace: ['thick brick'] },
  { label: 'buckeye' },
  { label: 'buckshot' },
  { label: 'buddha', replace: ['buddy buddha', 'buddha statue'] },
  { label: 'buffet' },
  { label: 'bulge' },
  { label: 'burrito' },
  { label: 'bumper', replace: ['bumper', 'goat bumper'] },
  { label: 'bunker', replace: ['bunker buster'] },
  { label: 'butler', replace: ['butler'] },
  { label: 'candle', replace: ['candle stick', 'curved candle'] },
  { label: 'cannon', replace: ['cannon', 'crotch-mounted regret cannon'] },
  { label: 'catapult', replace: ['dna catapult'] },
  { label: 'cattle prod' },
  { label: 'cave', replace: ['albino cave dweller'] },
  { label: 'cigar' },
  { label: 'citizen' },
  { label: 'chasm', replace: ['chasm closer'] },
  { label: 'cigar', replace: ['cigar', 'man cigar'] },
  { label: 'cinnamon', replace: ['cinnamon stick', 'cinnamon bun'] },
  { label: 'clam', replace: ['clam hammer', 'clam skewer'] },
  { label: 'cock' },
  { label: 'colossus' },
  { label: 'comet' },
  { label: 'compass', replace: ['crotch compass'] },
  { label: 'constrictor' },
  { label: 'corkscrew' },
  { label: 'corn', replace: ['corn on the cob'] },
  { label: 'crank' },
  { label: 'crocodile', replace: ['hole-hungry crotch crocodile'] },
  { label: 'cucumber' },
  { label: 'cyclops' },
  { label: 'dagger', replace: ['mutton dagger'] },
  { label: 'dangle', replace: ['dangle', 'dangle blaster'] },
  { label: 'dick' },
  { label: 'dipstick' },
  { label: 'dispenser', replace: ['dispenser', 'lotion dispenser'] },
  { label: 'diver', replace: ['gash diver'] },
  { label: 'divorce', replace: ['grounds for divorce'] },
  { label: 'dong' },
  { label: 'donkey', replace: ['bow-legged swamp donkey'] },
  { label: 'donut', replace: ['donut holder'] },
  { label: 'doughnut', replace: ['doughnut holder'] },
  { label: 'drill' },
  { label: 'drumstick', replace: ['drumstick', `colonel's drumstick`] },
  { label: 'dwarf' },
  { label: 'eel', replace: ['bathtub eel'], exactMatch: true },
  { label: 'eiffel tower' },
  { label: 'factory', replace: ['mayonnaise factory'] },
  { label: 'fairy', replace: ['throb fairy'] },
  { label: 'faucet', replace: ['genetic faucet'] },
  { label: 'ferret' },
  { label: 'finger', replace: ['finger food', `god's pinkey finger`] },
  { label: 'firecracker' },
  { label: 'fist', replace: ['monkey fist'] },
  { label: 'floppy' },
  { label: 'flute', replace: ['skin flute'] },
  { label: 'fist' },
  { label: 'friend', exactMatch: true },
  { label: 'fruit cake' },
  { label: 'gargoyle', replace: ['gargle gargoyle'] },
  { label: 'geyser', replace: ['fuck geyser'] },
  { label: 'giraffe', replace: ['giraffe neck'] },
  { label: 'goblin', replace: ['giggly goblin'] },
  { label: 'gollum' },
  { label: 'good start' },
  { label: 'goomba' },
  { label: 'gorilla', replace: ['gorilla vine'] },
  { label: 'grail', replace: ['holy grail'] },
  { label: 'groot' },
  { label: 'growth' },
  { label: 'gun', replace: ['glory gun'] },
  {
    label: 'hammer',
    replace: ['beef hammer', 'crunk hammer', 'hammerhead', 'hymen hammer'],
  },
  { label: 'handle', replace: ['giggle handle'] },
  { label: 'hershey bar' },
  { label: 'honey', replace: ['honey dripper'] },
  { label: 'hook', replace: ['gash hook', 'meat hook'] },
  { label: 'horn' },
  { label: 'hose', replace: ['milk hose', 'meat hose'], exactMatch: true },
  { label: 'iguana' },
  { label: 'inch', exactMatch: true },
  { label: 'inchworm' },
  { label: 'injector', replace: ['ass injector'] },
  { label: 'institution' },
  { label: 'jack in the box' },
  { label: 'jaw', replace: ['jawbreaker', 'jaw dropper'] },
  { label: 'jedi', replace: ['pocket jedi'] },
  { label: 'jimmy', replace: ['jimmy', 'jimmy dean', 'jimmy-jam'] },
  { label: 'johnson' },
  { label: 'joker' },
  { label: 'joystick' },
  { label: 'junk' },
  { label: 'kickstand' },
  { label: 'knee', replace: ['knee buckler'] },
  { label: 'knife' },
  { label: 'knob', replace: ['joy knob'] },
  { label: 'kryptonite', replace: ['kryptonite', 'bar of kryptonite'] },
  { label: 'ladder', replace: ['one-rung ladder'] },
  { label: 'lance', exactMatch: true },
  { label: 'laser pointer' },
  { label: 'lizard', replace: ['lap lizard'] },
  { label: 'llama' },
  { label: 'list', exactMatch: true },
  { label: 'little guy' },
  { label: 'loch ness monster' },
  { label: 'log', replace: ['lincoln log'], exactMatch: true },
  { label: 'logger' },
  { label: 'lure', exactMatch: true },
  { label: 'mallet', replace: ['gash mallet'] },
  { label: 'meat', exactMatch: true },
  { label: 'member' },
  { label: 'miner', replace: ['poo miner'] },
  { label: 'missile', replace: ['missile', 'man missile'] },
  { label: 'monkey', replace: ['monkey', 'cheeky monkey'] },
  { label: 'monster', replace: ['monster', 'red-headed throb monster'] },
  { label: 'monument' },
  { label: 'mountain' },
  { label: 'muffin', replace: ['bumble muffin'] },
  { label: 'mushroom' },
  { label: 'mustache', replace: ['mustache cleaner'] },
  { label: 'mystery meat' },
  { label: 'narwhal' },
  { label: 'needle', replace: ['needle', 'space needle'] },
  { label: 'neighbor', replace: ['downstairs neighbor'] },
  { label: 'ninja', replace: ['groin ninja'] },
  { label: 'noodle' },
  { label: 'obelisk' },
  { label: 'observer', replace: ['one-eye observer', 'ovary observer'] },
  { label: 'organ' },
  { label: 'pacifier' },
  { label: 'package' },
  { label: 'paddle', replace: ['crotch paddle'] },
  { label: 'paintbrush', replace: ['one-color paintbrush'] },
  { label: 'pecker' },
  { label: 'pee-pee' },
  { label: 'pee-wee' },
  { label: 'peen' },
  { label: 'pencil' },
  { label: 'peter' },
  { label: 'phallus' },
  { label: 'pickle' },
  { label: 'pin', replace: ['giggle pin'], exactMatch: true },
  { label: 'pipe', replace: ['agent hosepipe'] },
  { label: 'pistol' },
  {
    label: 'piston',
    replace: ['dude piston', 'fuck piston', 'thunder piston'],
  },
  { label: 'poker', replace: ['panty poker'] },
  { label: 'pole', replace: ['fuck pole', 'tent pole'] },
  { label: 'pope', replace: ['pope of pork'] },
  {
    label: 'popsicle',
    replace: ['popsicle', 'meat popsicle', 'pelvic popsicle'],
  },
  { label: 'powerpoint' },
  { label: 'prick' },
  { label: 'puppet', replace: ['man puppet', 'meat puppet'] },
  { label: 'python' },
  { label: 'railgun' },
  {
    label: 'ram',
    replace: ['batter ram', 'battering ram', 'mountain ram'],
    exactMatch: true,
  },
  { label: 'rattle', replace: ['booty rattle'] },
  { label: 'redwood' },
  {
    label: 'regret',
    replace: ['regret', 'ranger regret', 'symphony of regret'],
  },
  { label: 'relic' },
  { label: 'rifle', replace: ['cougar rifle'] },
  {
    label: 'rocket',
    replace: ['crotch rocket', 'girth rocket', 'red rocket'],
    exactMatch: true,
  },
  { label: 'rocket ship', replace: ['rocket ship to destiny'] },
  {
    label: 'rod',
    replace: ['rod', 'romance rod', 'vomit rod'],
    exactMatch: true,
  },
  { label: 'root', replace: ['man root'] },
  { label: 'saber', replace: ['saber', 'light saber'] },
  {
    label: 'sausage',
    replace: [
      'sausage',
      'blood sausage',
      'kielbasa sausage',
      'live sausage',
      'organic sausage',
      'succulent sausage',
    ],
  },
  { label: 'scarf', replace: ['beef scarf'] },
  { label: 'seat', exactMatch: true },
  { label: 'seatbelt' },
  { label: 'shaft' },
  { label: 'shovel', replace: [`satan's shovel`] },
  { label: 'sliver', replace: ['long dong sliver'] },
  { label: 'slug', replace: ['fuck slug'] },
  {
    label: 'snake',
    replace: [
      'bed snake',
      'bush snake',
      'trouser snake',
      'silk snake',
      'tube snake',
      'tunnel snake',
    ],
  },
  { label: 'spatula' },
  { label: 'spelunker' },
  { label: 'steak', replace: ['steak', 'quiver steak'], exactMatch: true },
  { label: 'steel', replace: ['steel'] },
  { label: 'steeple' },
  {
    label: 'stick',
    replace: [
      'fuck stick',
      'glue stick',
      'gut stick',
      'laugh stick',
      'pool stick',
      'puff stick',
      'drizzle-stick',
      'suckstick',
      'walking stick',
    ],
  },
  { label: 'stimulus', replace: ['stimulus', 'stimulus package'] },
  { label: 'stinger' },
  { label: 'stingray' },
  { label: 'straw', replace: ['straw', 'meat straw', 'milk straw'] },
  { label: 'stump' },
  { label: 'surprise' },
  { label: 'sword', replace: ['sword', 'squish sword'] },
  { label: 'tail', replace: ['front tail'] },
  { label: 'thermometer' },
  { label: 'thing', exactMatch: true },
  { label: 'throttle', replace: ['gobble throttle'] },
  { label: 'tool' },
  { label: 'tooth', replace: [`dragon's tooth`] },
  { label: 'toothpick' },
  { label: 'torch' },
  { label: 'torpedo', replace: ['torpedo', 'tadpole torpedo'] },
  { label: 'tower', replace: ['tower', 'leaning tower'], exactMatch: true },
  { label: 'tree', replace: ['branch of the man-tree', 'the giving tree'] },
  {
    label: 'troll',
    replace: ['troll', 'cave troll', 'forest troll', 'mountain troll'],
  },
  { label: 'trunk', replace: ['elephant trunk'] },
  { label: 'turkey', replace: ['turkey baster'] },
  { label: 'turtle' },
  { label: 'twinkie' },
  { label: 'twizzler', replace: ['twizzler', 'passion twizzler'] },
  { label: 'usb', replace: ['usb stick'] },
  { label: 'unicorn' },
  { label: 'vibrator' },
  { label: 'vine', replace: ['gorilla vine', 'vine'], exactMatch: true },
  { label: 'wand' },
  { label: 'wang' },
  {
    label: 'warrior',
    replace: ['warrior', 'lone warrior', 'one-eyed warrior'],
  },
  { label: 'weasel' },
  { label: 'whale' },
  { label: 'whistle', replace: ['whistle', 'friction whistle'] },
  { label: 'wiener' },
  { label: 'willy' },
  { label: 'wine', replace: ['bottle of wine'] },
  { label: 'winkey' },
  { label: 'winky', replace: ['winky', 'captain winky'] },
  { label: 'wood' },
  { label: 'worm', replace: ['adventure worm'] },
]

export default synonyms
