export interface Synonym {
  label: string
  replace?: string[]
  exactMatch?: boolean
}

export const synonyms: Synonym[] = [
  { label: '2x4' },
  { label: '9-iron' },
  { label: 'aardvark' },
  { label: 'acorn', replace: ['acorn top'] },
  { label: 'anaconda' },
  { label: 'antenna' },
  {
    label: 'apple',
    replace: [
      'apple head',
      'apple-headed beef basher',
      'apple on a short branch',
    ],
  },
  { label: 'aux cord' },
  { label: 'baby', replace: ['baby leg', 'baby maker'] },
  { label: 'back scratcher' },
  { label: 'banana' },
  { label: 'bandit' },
  { label: 'boa constrictor' },
  { label: 'bazooka' },
  { label: 'beanie baby' },
  { label: 'beanstalk' },
  {
    label: 'beast',
    replace: ['beast of burden', 'below the belt bacon beast', 'beefy bastard'],
  },
  { label: 'bigfoot' },
  { label: 'binky' },
  { label: 'blowpop' },
  { label: 'blunderbuss' },
  { label: 'bone' },
  { label: 'branch' },
  { label: 'buckeye' },
  { label: 'buckshot' },
  { label: 'buddha', replace: ['buddy buddha', 'buddha statue'] },
  { label: 'buffet' },
  { label: 'bulge' },
  { label: 'bunker', replace: ['bunker buster'] },
  { label: 'butler', replace: ['butler'] },
  { label: 'cannon', replace: ['cannon', 'crotch-mounted regret cannon'] },
  { label: 'cattle prod' },
  { label: 'citizen' },
  { label: 'chasm', replace: ['chasm closer'] },
  { label: 'cinnamon', replace: ['cinnamon stick', 'cinnamon bun'] },
  { label: 'clam', replace: ['clam hammer', 'clam skewer'] },
  { label: 'cock' },
  { label: 'colossus' },
  { label: 'comet' },
  { label: 'compass', replace: ['crotch compass'] },
  { label: 'corkscrew' },
  { label: 'corn on the cob' },
  { label: 'crank' },
  { label: 'cucumber' },
  { label: 'cyclops', replace: ['crying cyclops'] },
  { label: 'dick' },
  { label: 'donkey', replace: ['bow-legged swamp donkey'] },
  { label: 'eel', replace: ['bathtub eel'], exactMatch: true },
  { label: 'floppy' },
  { label: 'fruit cake' },
  { label: 'good start' },
  { label: 'hammer', replace: ['beef hammer', 'crunk hammer', 'hammerhead'] },
  { label: 'handle' },
  { label: 'injector', replace: ['ass injector'] },
  { label: 'institution' },
  { label: 'kryptonite', replace: ['kryptonite', 'bar of kryptonite'] },
  { label: 'llama' },
  { label: 'logger' },
  { label: 'monkey', replace: ['monkey', 'cheeky monkey'] },
  { label: 'muffin', replace: ['bumble muffin'] },
  { label: 'mustache', replace: ['unconvincing mustache'] },
  { label: 'paddle', replace: ['crotch paddle'] },
  { label: 'pipe', replace: ['agent hosepipe'] },
  {
    label: 'ram',
    replace: ['batter ram', 'battering ram', 'mountain ram'],
    exactMatch: true,
  },
  { label: 'rattle', replace: ['booty rattle'] },
  { label: 'regret' },
  { label: 'relic' },
  { label: 'rifle', replace: ['cougar rifle'] },
  { label: 'rocket', replace: ['crotch rocket'], exactMatch: true },
  { label: 'rocket ship', replace: ['rocket ship to destiny'] },
  {
    label: 'sausage',
    replace: ['sausage', 'blood sausage', 'kielbasa sausage'],
  },
  { label: 'scarf', replace: ['beef scarf'] },
  { label: 'seat', exactMatch: true },
  { label: 'seatbelt' },
  { label: 'slug' },
  { label: 'snake', replace: ['bed snake', 'bush snake', 'trouser snake'] },
  { label: 'steel', replace: ['steel'] },
  { label: 'stinger' },
  { label: 'tree', replace: ['branch of the man-tree'] },
  {
    label: 'troll',
    replace: ['troll', 'cave troll', 'forest troll', 'mountain troll'],
  },
  { label: 'turtle' },
  { label: 'vibrator' },
  { label: 'wine', replace: ['bottle of wine'] },
  { label: 'winkey' },
  { label: 'winky', replace: ['winky', 'captain winky'] },
  { label: 'worm', replace: ['adventure worm'] },
  // `Cucumber`,
  // `Cum Cannon`,
  // `Cum Gutter`,
  // `Cum-Breathing Dragon`,
  // `Cunt Cockula`,
  // `Cupids Arrow`,
  // `Cupids Torch`,
  // `Curved Candle`,
  // `Curved Majesty`,
  // `D-Battery`,
  // `Daddy's Hand Gun`,
  // `Dangle Blaster`,
  // `Dangle`,
  // `Dangus`,
  // `Dead Eye Sam`,
  // `Dearest Member`,
  // `Deep Digger`,
  // `Deep Impact`,
  // `Deep Personal-Space Probe`,
  // `Defender of the City`,
  // `Defiler of Many`,
  // `Demon of the South Side`,
  // `Denim Ferret`,
  // `Denim Narwhal`,
  // `Derier Defiler`,
  // `Devourer of Worlds`,
  // `Diamond Cracker`,
  // `Dick`,
  // `Dick`,
  // `Dickapult`,
  // `Diddle-Whistle`,
  // `Diddly`,
  // `Didjeri-Don't`,
  // `Ding-a-ling`,
  // `Ding-Dong-Dangly`,
  // `Ding-dong`,
  // `Dingaling`,
  // `Dinger`,
  // `Dingle`,
  // `Dingus`,
  // `Dingy`,
  // `Dink`,
  // `Dinkle`,
  // `Dinky`,
  // `Dipstick`,
  // `Dirty Dowsing Rod`,
  // `Dirty Ice Cream Cone`,
  // `Dirty Jammer`,
  // `Dirty Mushroom`,
  // `Dirty Thermometer`,
  // `DNA Catapult`,
  // `Doctor Howler`,
  // `Dome Head`,
  // `Dong`,
  // `Dong`,
  // `Dongasaurous Rex`,
  // `Donger`,
  // `Dongmongulous`,
  // `Dongzilla`,
  // `Doodle`,
  // `Dough Boy`,
  // `Doughnut Holder`,
  // `Dr. Feelgood`,
  // `Dragon's Tooth`,
  // `Drill Sergeant`,
  // `Drippy Paintbrush`,
  // `Drippy Puffer-Fish`,
  // `Drizzle Spout`,
  // `Drooling Badger`,
  // `Droopy Baguette With Cheese`,
  // `Droopy Dog`,
  // `Drumstick`,
  // `Duck Call`,
  // `Dude Piston`,
  // `Dunce Hat`,
  // `E.T.'s Finger`,
  // `Earthworm Jim`,
  // `Edward Norton in American History X`,
  // `Eiffel Tower`,
  // `Eighth Wonder of the World`,
  // `Electric Boogaloo`,
  // `Elephant Trunk`,
  // `Elevator`,
  // `Erected Evolution`,
  // `Erector`,
  // `Escape Rope`,
  // `Escape Rope`,
  // `Excalibur`,
  // `Eye Dropper`,
  // `Eye of the Pleasure-Storm`,
  // `Eye Of The Storm`,
  // `Eye Piercer`,
  // `Face Blaster`,
  // `Face Hugger`,
  // `Fanny Slapper`,
  // `Fappling Gun`,
  // `Fat Kidney`,
  // `Fat Stick`,
  // `Father of Dragons`,
  // `Festering Growth`,
  // `Fiddle-Bow`,
  // `Filler`,
  // `Filthy Fornicator`,
  // `Filthy Spelunker`,
  // `Finger Food`,
  // `Fire Spout`,
  // `Firecracker`,
  // `Fist of Fury`,
  // `Flaming Face Slapper`,
  // `Flamingos Beak`,
  // `Flayer of Mortals`,
  // `Flesh Auger`,
  // `Flesh Flute`,
  // `Flesh Hawk`,
  // `Flesh Root`,
  // `Flesh Saber`,
  // `Flesh-Zeppelin`,
  // `Fleshy Bong`,
  // `Fleshy Iceberg`,
  // `Fleshy Pacifier`,
  // `Flex Rod`,
  // `Flop Trout`,
  // `Flop-Handle`,
  // `Floppy Fish`,
  // `Floppy Meat Balloon`,
  // `Fountain of Youth`,
  // `Friction Whistle`,
  // `Friendly Downstairs Neighbor`,
  // `Front Tail`,
  // `Frothy Flotilla`,
  // `Fruit Bearer`,
  // `Fuck Geyser`,
  // `Fuck Loaf`,
  // `Fuck Maker`,
  // `Fuck Piston`,
  // `Fuck Slug`,
  // `Fuckarina of Time`,
  // `Fucknado`,
  // `Fuckpole`,
  // `Fuckstick`,
  // `Fur Blimp`,
  // `Furious Downstairs Neighbor`,
  // `Furry Fuzz-Fucker`,
  // `Furry Snake`,
  // `Fury Faucet`,
  // `Fury Monkey`,
  // `Fury of the River`,
  // `Future Destroyer`,
  // `Fuzz Baton`,
  // `Fuzz Nugget`,
  // `Gandalf's Staff`,
  // `Ganker`,
  // `Gargle Gargoyle`,
  // `Gash Diver`,
  // `Gash Hook`,
  // `Gash Mallet`,
  // `General McSexy`,
  // `General Throb`,
  // `Genetic Faucet`,
  // `Genghis Cock`,
  // `genitalia`,
  // `Giggle Handle`,
  // `Giggle Pin`,
  // `Giggly Goblin`,
  // `Giraffe Neck`,
  // `Girth Rocket`,
  // `Gleaming Love Blade`,
  // `Glorious Peoples Leader`,
  // `Glory Gun`,
  // `Glue Stick`,
  // `Goal-Post`,
  // `Goat Bumper`,
  // `Gobble Throttle`,
  // `Gods Pinkey Finger`,
  // `Golden Spigot`,
  // `Goldenrod`,
  // `Gollum`,
  // `Gonadulous`,
  // `Gong-Ringer`,
  // `Gonorrhea Giver`,
  // `Goomba`,
  // `Gorilla Vine`,
  // `Grave Digger`,
  // `Greasy Fish`,
  // `Greasy Gator`,
  // `Gristle`,
  // `Groin Gouger`,
  // `Groin Graboid`,
  // `Groin Ninja`,
  // `Groot`,
  // `Grounds For Divorce`,
  // `Growth`,
  // `Grunt Rod`,
  // `Grunty Grunty Thrust Thrust`,
  // `Guardian Angel With a Substance Abuse Problem`,
  // `Gut Stick`,
  // `Hairless Ferret`,
  // `Hairy Banjo`,
  // `Hairy Houdini`,
  // `Hairy How-Do-You-Do`,
  // `Hairy Pen`,
  // `Half a Necklace`,
  // `Half of a Good Time`,
  // `Ham Branch`,
  // `Ham Dragon`,
  // `Ham Tube`,
  // `Hammer of Dawn`,
  // `Hammer of God`,
  // `Hammer`,
  // `Hammy Toothpick`,
  // `Handle`,
  // `Handy Hammer`,
  // `Hangy-Downy`,
  // `Harbinger of the End Times`,
  // `He-Who-Shall-Not-Be Named`,
  // `Head of Public Relations`,
  // `Heat Seeking Moisture Missile`,
  // `Herp Head`,
  // `Herpes Hammer`,
  // `Hershey Bar`,
  // `Hibernating Bear`,
  // `Highway to the Danger Zone`,
  // `Holy Grail`,
  // `Holy Grail`,
  // `Honey Dripper`,
  // `Honky-Honky`,
  // `Hooker Hammer`,
  // `Hornets Sting`,
  // `Hot Beef Injection`,
  // `Hot Pocket`,
  // `Hotrod`,
  // `Hotrod`,
  // `Hulk's Fist`,
  // `Hunchback of Notre Dame`,
  // `Hymen Hammer`,
  // `Ice Pick`,
  // `Iguana`,
  // `Impractical Paintbrush`,
  // `Inchworm`,
  // `Ineffective Scope`,
  // `Inflatable Poo-Jabber`,
  // `Inside-the-Pants-Belt`,
  // `Italian Stallion`,
  // `Jack in the Box`,
  // `Jean Steak`,
  // `Jelly Roll`,
  // `Jenga Tower`,
  // `Jericho Missile`,
  // `Jigger`,
  // `Jiggly Wiggly`,
  // `Jimmy Dean Reject`,
  // `Jimmy Dean`,
  // `Jimmy-Jam`,
  // `Jimmy`,
  // `Jizzstick`,
  // `John Thomas`,
  // `johnson`,
  // `Johnson`,
  // `Joker`,
  // `Joy Knob`,
  // `Joystick`,
  // `Juicer`,
  // `Juicy Dribbler`,
  // `Juicy Man Steak`,
  // `Jumbotron`,
  // `Junk In the Jeans`,
  // `Just Mind Bogglingly Girthy-Bore Rifle`,
  // `Kaleidoscope of Pleasure`,
  // `Key Part of the Male Reproductive System`,
  // `Key to the End Times`,
  // `Key to Your Dreams`,
  // `Khal Drogo`,
  // `Kickstand`,
  // `Knee Buckler`,
  // `Knob`,
  // `Lady Gag-you`,
  // `Lambshank`,
  // `Lance of Love`,
  // `Lap Lizard`,
  // `Large Bore Rifle`,
  // `Laser Pointer`,
  // `Laser Splitter`,
  // `Laugh Stick`,
  // `Leaning Tower`,
  // `Legwarmer`,
  // `Lethal Injection`,
  // `Life Preserver`,
  // `Life Sprinkler`,
  // `Lifeline`,
  // `Light Saber`,
  // `Lightning Catcher`,
  // `Lil' Winkey`,
  // `Limited Depth Drilling Apparatus`,
  // `Lincoln Log`,
  // `Lipstick`,
  // `Liquid Almost-Baby Faucet`,
  // `Little (Insert Your Own Name Here)`,
  // `Little Dovahkiin`,
  // `Little Engine That Could`,
  // `Little Fucker`,
  // `Little Guy With the Least Fashionable Turtle-Neck Sweater of All Time`,
  // `Little Guy`,
  // `Live Sausage`,
  // `Loch Ness Monster`,
  // `Long Dong Sliver`,
  // `Long N' Girthy`,
  // `Long Pig`,
  // `Lord Commander Groinulous`,
  // `Lord Commander of the Southern Forces`,
  // `Lord Humongous`,
  // `Lord of Light`,
  // `Lord of the Halls of Madness`,
  // `Lotion Dispenser`,
  // `Love Belcher`,
  // `Love Lure`,
  // `Love Lure`,
  // `Love Shaft`,
  // `Loveworm`,
  // `Lumpy`,
  // `Lust Powered Coat Hanger`,
  // `Lust Torch`,
  // `Lusty Love Lance`,
  // `Mad Max`,
  // `Magic Mountain`,
  // `Magic Pipe`,
  // `Main Drain`,
  // `Man Bits`,
  // `Man Clit`,
  // `Man Drain`,
  // `Man Horn`,
  // `Man Missile`,
  // `Man Nugger`,
  // `Man Puppet`,
  // `Man Root`,
  // `Man Telescope`,
  // `Man-Motor`,
  // `Mandana`,
  // `Mangler`,
  // `manhood`,
  // `Manly Cigar`,
  // `Manly Shrub-Hub`,
  // `Master Sword`,
  // `Masturbation Motor`,
  // `Mayonnaise Factory`,
  // `Mayonnaise Pipeline`,
  // `Mayor of Pants City`,
  // `Meat Stick`,
  // `Meat Storm`,
  // `Meat Straw`,
  // `Meat-hose`,
  // `Meat-Lolly`,
  // `Meat`,
  // `Meatstick`,
  // `Meaty Bubble-Wand`,
  // `Meaty Maelstrom`,
  // `Mega Shark`,
  // `member`,
  // `member`,
  // `Mentos and Coke`,
  // `Messy Burrito`,
  // `Metapod`,
  // `Midget Chaser`,
  // `Mightiest Tree In the Forest`,
  // `Mighty Blade`,
  // `Mighty Unicorn Horn`,
  // `Milk Dripper`,
  // `Milk Hose`,
  // `Milk Straw`,
  // `Mjolnir`,
  // `Monkey Fist`,
  // `Monkey String`,
  // `Monkey`,
  // `Monument`,
  // `Moses`,
  // `Mossy Sea Slug`,
  // `Mount Doom`,
  // `Mount St. Helens`,
  // `Mr. Bojangles`,
  // `Mr. Clean`,
  // `Mr. Happy`,
  // `Mr. Hornbag`,
  // `Mr. Meowsworth`,
  // `Mr. Missile`,
  // `Mr. Sniffles`,
  // `Mt. Everest`,
  // `Muscle Bound Shit Wrecker`,
  // `Musk Handle`,
  // `Musky Man Candy`,
  // `Mustache Cleaner`,
  // `Mutton Dagger`,
  // `My Best Friend`,
  // `My Body's Captain`,
  // `My Fleshy Friend`,
  // `My Manly Popsicle`,
  // `My Personal Stradovarious`,
  // `My Rifle`,
  // `Mystery Meat`,
  // `Natural Second Nose`,
  // `Needler`,
  // `Nimrod`,
  // `No-Knuckle Pants Finger`,
  // `Nose In the Beard`,
  // `Number One Pencil`,
  // `Ocarina of Slime`,
  // `Ol' Drippy`,
  // `Ol' Faithful`,
  // `Ol' Fisty`,
  // `Old Frothy`,
  // `Old Man Drizzle`,
  // `One Color Paintbrush`,
  // `One Color Rainbow`,
  // `One Eyed Man`,
  // `One Flower Bouquet`,
  // `One Nostril Nose Plug`,
  // `One Rung Ladder`,
  // `One String Guitar`,
  // `One-Eyed Yogurt Thrower`,
  // `Organic Sausage`,
  // `Ovary Observer`,
  // `Package`,
  // `Package`,
  // `Pants Boomerang`,
  // `Pants Muffler`,
  // `Pants Politician`,
  // `Panty Poker`,
  // `Parental Distillery`,
  // `Passion Twizzler`,
  // `Peacemaker`,
  // `Pearl Jamer`,
  // `Pearl Necklace Provider`,
  // `Pecker-Corn`,
  // `pecker`,
  // `Pecker`,
  // `Pecker`,
  // `Pee-pee`,
  // `Pee-Pee`,
  // `Pee-Wee Herman`,
  // `Pee-wee`,
  // `Peen`,
  // `Peen`,
  // `Peeper`,
  // `Pelvic Popsicle`,
  // `Penis`,
  // `Penis`,
  // `Period Plugger`,
  // `Personal Baseball Bat`,
  // `Personal On Switch`,
  // `Personal Piglet`,
  // `peter`,
  // `Peter`,
  // `phallus`,
  // `Phallus`,
  // `Phantom of the Opera In Your Pants`,
  // `Philly Cheese-steak`,
  // `Pickle`,
  // `Piddle Fiddle`,
  // `Pillar of Awesome`,
  // `Pink Floyd`,
  // `Pink Kink Handle`,
  // `Pink Pencil`,
  // `Pink Tractor Beam`,
  // `Pink Xenomorph`,
  // `Pinkey and the Brain`,
  // `Pipe Cleaner`,
  // `Piss Dispenser`,
  // `Piss Pump`,
  // `Pisser`,
  // `Pistol`,
  // `Pixy Stick`,
  // `Plaster Blaster`,
  // `Pleasure Bud`,
  // `Pleasure Gavel`,
  // `Pleasure Machine`,
  // `Pleasure Pogo`,
  // `Pleasure Rod`,
  // `Plonker`,
  // `Pneumatic Navel Nudger`,
  // `Pocket Jedi`,
  // `Pocket Shot Glass`,
  // `Poo Miner`,
  // `Poo-Flicker`,
  // `Pool Stick`,
  // `Pop-Tart`,
  // `Pope of Pork`,
  // `Pork Blade`,
  // `Pork Lance`,
  // `Pork Pawn`,
  // `Pork Pipe`,
  // `Pork Spatula`,
  // `Pork Steeple`,
  // `Pork Whistle`,
  // `Pork-Stalk`,
  // `Power Point`,
  // `Pressure Washer`,
  // `prick`,
  // `Pringle's Tube`,
  // `Private Washington Monument`,
  // `Problem For the Local Zoning Commission`,
  // `Professor XXX`,
  // `Proof God Has a Sense of Humor`,
  // `Puff Stick`,
  // `Puff the One-Eyed Dragon`,
  // `Pug Face`,
  // `Puking Flesh Weasel`,
  // `Pull Up Bar`,
  // `Pump Action Shotgun`,
  // `Purple Pneumatic Drill`,
  // `Purple Turkey Baster`,
  // `Purple Warrior`,
  // `Purple-Headed Man Monster`,
  // `Pussy Pounder`,
  // `Pussy Pulverizer`,
  // `putz`,
  // `Python`,
  // `Queef Creator`,
  // `Quelaags Fury Sword`,
  // `Quick-Scope`,
  // `Quickening Peg`,
  // `Quiver Bone`,
  // `Quiver Steak`,
  // `Rabid Dog`,
  // `Radio Tower`,
  // `Rage Burrower`,
  // `Railgun`,
  // `Rainbow Maker`,
  // `Rainstick`,
  // `Ranger Regret`,
  // `Reason to Consult a Medical Professional`,
  // `Rectal Wrecker`,
  // `Red Cap`,
  // `Red Headed Throb Monster`,
  // `Red Hot Toy`,
  // `Red Rocket`,
  // `Redwood`,
  // `Regurgitator`,
  // `Respectable Gentleman`,
  // `Rip Van Winkey`,
  // `Rip-Chord`,
  // `Road to Pleasure`,
  // `Rock Em Sock Em Robot`,
  // `Rocket-Top Bottle`,
  // `Rolling Pin`,
  // `Romance Rod`,
  // `Rump Plug`,
  // `Russel the One-Eyed Wonder Weasel`,
  // `Sad Larry`,
  // `Salty Drizzle-Stick`,
  // `Salty Geyser`,
  // `Salty Steve`,
  // `Satan Scepter`,
  // `Satan's Shovel`,
  // `Saucy Noodle`,
  // `Scepter of Sordid Affairs`,
  // `Scepter`,
  // `schlong`,
  // `Schlong`,
  // `Schlong`,
  // `Schlort`,
  // `Seamen Spitter`,
  // `Second Brain`,
  // `Sergeant Slaughter`,
  // `Serpentine Surprise`,
  // `Sex Reactor`,
  // `Sexy Suppository`,
  // `shaft`,
  // `Shaft`,
  // `Shaft`,
  // `Shagger`,
  // `Shake-Weight`,
  // `Sham-WOW!`,
  // `Shifty Wrinkle-Demon`,
  // `Shlong`,
  // `Showerhead`,
  // `Shrinky Dink`,
  // `Shroomy`,
  // `Silk Snake`,
  // `Sin Stick`,
  // `Six Inch Soldier`,
  // `Skin flute`,
  // `Slammin' Salmon`,
  // `Slim Jim`,
  // `Slippery Love Dolphin`,
  // `Slippery Salmon`,
  // `Slippery Snake`,
  // `Slippy`,
  // `Sludge Pump`,
  // `Slytherin`,
  // `Small-Bore Rifle`,
  // `Smeagol`,
  // `Smelly Dwarf`,
  // `Smile Spreader`,
  // `Smokeless Peace Pipe`,
  // `Snake With the Lazy Eye`,
  // `Snatch Ratchet`,
  // `Snow Globe`,
  // `Snowpiercer`,
  // `Sock Cruster`,
  // `Sock Stiffener`,
  // `Soft Knife`,
  // `Sonic Screwdriver`,
  // `Sour Cream Rifle`,
  // `Sour Creme Production Facility`,
  // `Source of the Local Syphilis Outbreak`,
  // `Space Needle`,
  // `Spam Obelisk`,
  // `Sparkle Bolt`,
  // `Spelunker`,
  // `Sperm Spraying Whale`,
  // `Spice Shaker`,
  // `Spikey-Back Turtle-Dragon`,
  // `Spitting Cobra`,
  // `Splooge McDuck`,
  // `Splooge Saber`,
  // `Sploogy Sharpshooter`,
  // `Spray Stick`,
  // `Spring Loaded Semen Sprayer`,
  // `Spring-Loaded Nose-Slapper`,
  // `Spunk Catapult`,
  // `Squinty Blow-pop`,
  // `Squirm-Handle`,
  // `Squirtle`,
  // `Squish Sword`,
  // `Sriracha Dripper`,
  // `Starscream`,
  // `Stay Pufft`,
  // `Steve Buscemi's Face`,
  // `Stick of Sexy Dynamite`,
  // `Sticky Ass-Spackler`,
  // `Sticky Cigar`,
  // `Sticky Taser`,
  // `Stimulus Package`,
  // `Sting Ray`,
  // `Stink Twizzler`,
  // `Strawberry Ice Cream Cone`,
  // `Stump`,
  // `Submarine`,
  // `Succulent Sausage`,
  // `Suckshroom`,
  // `Suckstick`,
  // `Suppository`,
  // `Sushi Roll`,
  // `Sweatsicle`,
  // `Sweaty Suck-Stick`,
  // `Sweet Meat`,
  // `Sword of Michael`,
  // `Symphony of Regret`,
  // `Syphilis Saber`,
  // `Syrupy Cylinder Waffle`,
  // `Taco Warmer`,
  // `Tadpole Torpedo`,
  // `Tallywhacker`,
  // `Tan Banana`,
  // `Tapioca Tap`,
  // `Target`,
  // `Teeth Whitener`,
  // `Temporary Vaginal Piercing`,
  // `Temptation Turtle`,
  // `Tent Pole`,
  // `Terms and Conditions`,
  // `The Actual Shocker`,
  // `The Albino Cave Dweller`,
  // `The Alien`,
  // `The Alpha`,
  // `The Banana Cannon`,
  // `The Beast`,
  // `The Blister Pistol`,
  // `The Blood God Atrofax`,
  // `The Brittlest Bone`,
  // `The Bulge`,
  // `The Business End`,
  // `The Colonels Drumstick`,
  // `The Conqueror`,
  // `The D`,
  // `The Dark Knight`,
  // `The De-Virginator`,
  // `The Devils Own Microphone`,
  // `The Elder Wand`,
  // `The Eternal Eviscerator`,
  // `The Eviscerator`,
  // `The Exactly-In-The-Middle Pole`,
  // `The Faceless Man`,
  // `The Fast`,
  // `The Fate of Many`,
  // `The Fibonacci Sequence`,
  // `The Folly of Man`,
  // `The Frothy Frigate`,
  // `The Furious`,
  // `The Giving Tree`,
  // `The Goods`,
  // `The Grand Finale`,
  // `The Grand Slamwich`,
  // `The Hive Mind`,
  // `The Hole-Hungry Crotch Crocodile`,
  // `The Horn of Gondor`,
  // `The Human Centipede`,
  // `The Intruder`,
  // `The Jowliest Old Man`,
  // `The Juice Crew`,
  // `The Juicer`,
  // `The Key to the Lock`,
  // `The Kingslayer`,
  // `The Larger Hand On Big Ben's Clock`,
  // `The Last Action Hero`,
  // `The Last Unicorn`,
  // `The Little Bruce Willis That Lives In My Pants`,
  // `The Littlest Gentleman`,
  // `The Lone Ranger`,
  // `The Lone Warrior`,
  // `The Long Hand On the Pants Clock`,
  // `The Mainline To Dirty-Town`,
  // `The Male Reproductive Organ`,
  // `The Man Behind the Curtain`,
  // `The Middle Muffin-Top`,
  // `The Mommy Maker`,
  // `The Monolith`,
  // `The North Pole`,
  // `The Ol' Aim N' Shoot`,
  // `The Ol' S Hook`,
  // `The Omega`,
  // `The Oncoming Storm`,
  // `The One Balloon That Doesn't Match`,
  // `The One Headed Hydra`,
  // `The Oscar Meyer Weenie`,
  // `The Pen That Never Runs Out Of Ink`,
  // `The Pendulum`,
  // `The Ramburglar`,
  // `The Really Big Lebowski`,
  // `The Reason I Come Up With Shortcuts That Keep Us Away From Elementary Schools`,
  // `The Reason I Have All of Those Children That I Hate`,
  // `The Riddler`,
  // `The Sappy Oak`,
  // `The Septapalegic Octopus`,
  // `The Short Crutch`,
  // `The South Pole`,
  // `The Spanish Inquisition`,
  // `The Speculum`,
  // `The Spreader`,
  // `The Star Spangled Banger`,
  // `The Thundering Overseer`,
  // `The Tree of Forbidden Fruit`,
  // `The Tree of Life`,
  // `The Troll of Thigh Valley`,
  // `The Troll`,
  // `The Ugliest Flower`,
  // `The Weeping Willow`,
  // `The Whip`,
  // `The White Whale of the Denim Seas`,
  // `The Whitest Walker`,
  // `The Whomping Willow`,
  // `The Yeast Feaster`,
  // `The Zipper-Caged Creature`,
  // `Thermonuclear Rod`,
  // `Thick Brick`,
  // `Third Eye Sam`,
  // `Third Leg`,
  // `Thirdleg`,
  // `Thrill Drill`,
  // `Thrill Mill`,
  // `Throat Cork`,
  // `Throat Scraper`,
  // `Throb Fairy`,
  // `Throbknob`,
  // `Thruster`,
  // `Thunder Piston`,
  // `Thunderhorse`,
  // `Thunderous Tootsie-Roll`,
  // `Thunderous Whip of Transcendent Fury`,
  // `Thunderstick`,
  // `Tic-Tac`,
  // `Tickle Badger`,
  // `Tickle-Gizzard`,
  // `Tirpitz`,
  // `Titty-Tickler`,
  // `Toe Scratcher`,
  // `Toilet Parts`,
  // `Tongue Tester`,
  // `Tongue Twister`,
  // `tool`,
  // `Tool`,
  // `Toothpaste Tube`,
  // `Tootsie Pop`,
  // `Toucan's Beak`,
  // `Toxic Tourniquet`,
  // `Trans-Pantslantic Cable`,
  // `Transformer`,
  // `Trebuchet With Very Disconcerting Ammunition`,
  // `Tremble Tumor`,
  // `Tremble Wand`,
  // `Trickle Torpedo`,
  // `Tripod`,
  // `Trouser monkey`,
  // `Trouser Snake`,
  // `Trouser Tsunami`,
  // `Trout-Trident`,
  // `Tube of Mascara`,
  // `Tubesnake`,
  // `Tunnel Snake`,
  // `Twat Fodder`,
  // `Twiddle Rhombus`,
  // `Twig and Berries`,
  // `Twinkie`,
  // `Two-Direction Compass`,
  // `Uncle Reamus`,
  // `Uncle Touchy's Happy Stick`,
  // `Under the Covers Crusader`,
  // `Upright Base`,
  // `Urchin`,
  // `USB Stick`,
  // `Vagina Miner`,
  // `Vagina Monster`,
  // `Vagina Plug`,
  // `Vaginal Eviscerator`,
  // `Vaginal Speculum`,
  // `Vaginal Sunrise`,
  // `Vein-Bow`,
  // `Veiny Cucumber`,
  // `Veiny Girth`,
  // `Veiny Straw`,
  // `Velvit Python`,
  // `Very Hot Topic`,
  // `Vesuvius`,
  // `Vlad the Impaler`,
  // `Volcano`,
  // `Voldemort's Missing Nose`,
  // `Vomit Rod`,
  // `Vomitous Mass`,
  // `Walking Stick`,
  // `Wang`,
  // `Wang`,
  // `Wankhammer`,
  // `Warp Pipe`,
  // `Weapon of Ass Destruction`,
  // `Weapon`,
  // `Web Slinger`,
  // `Wee-wee`,
  // `Weedle`,
  // `weenie`,
  // `Weeny`,
  // `Weeping Monkey`,
  // `Weepy Cobra`,
  // `weiner`,
  // `Weiner`,
  // `Whang`,
  // `Whistle`,
  // `Whoopi-Maker`,
  // `Wickless Candle`,
  // `wiener`,
  // `Wife Gagger`,
  // `Wiggle Finger`,
  // `Wiggle Worm`,
  // `Wiggly Pogo-Stick`,
  // `Wii-Mote`,
  // `Wild Hog`,
  // `Willie`,
  // `willy`,
  // `Wind Waker`,
  // `Winkey Badger`,
  // `Wolly Manmoth`,
  // `Woman Maker`,
  // `Woman-Slayer`,
  // `Womb Broom`,
  // `wood`,
  // `Woody Womb Pecker`,
  // `Worlds Cheapest Bottle of Champagne`,
  // `Worlds Least Appropriate Crucifix`,
  // `Worlds Shortest Fishing Pole`,
  // `Worlds Smallest Violin`,
  // `Worldstomper`,
  // `Wormtail`,
  // `Wrinklebeast`,
  // `Wrinklestiltskin`,
  // `Wrinkly Crutch`,
  // `X-Rated Toothpick`,
  // `Yellow Wine Dispenser`,
  // `Yogurt Truck`,
  // `Yoo-Hoo`,
  // `You-Know-Who`,
  // `Zamboni Bologna`,
  // `Zip-Code Extender`,
  // `Zipper Constrictor`,
]

export default synonyms
